# Generated by Django 3.0.3 on 2020-03-07 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200303_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('orderno', models.CharField(max_length=100)),
                ('shopname', models.CharField(max_length=100)),
                ('delstatus', models.BooleanField(default=False)),
                ('deltime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('orderno', models.CharField(max_length=100)),
                ('shopname', models.CharField(max_length=100)),
                ('orderdate', models.DateTimeField()),
                ('orderamount', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=50)),
                ('itemprice', models.CharField(max_length=100)),
                ('itemqty', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentdate',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='salesman',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='shopname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
