# Generated by Django 3.0.3 on 2020-03-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderdetail',
        ),
    ]
