# Generated by Django 3.0.3 on 2020-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20200309_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('orderno', models.CharField(max_length=100)),
                ('shopname', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop',
            field=models.IntegerField(),
        ),
    ]
