# Generated by Django 3.0.3 on 2020-03-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20200310_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='amount',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
