# Generated by Django 3.0.3 on 2020-03-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_distributordetail_salesmandetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributordetail',
            old_name='contactno',
            new_name='dcontactno',
        ),
    ]
