# Generated by Django 3.0.3 on 2020-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_auto_20200313_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributordetail',
            name='distributorid',
            field=models.IntegerField(null=True),
        ),
    ]
