# Generated by Django 3.0.3 on 2020-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_auto_20200313_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributordetail',
            name='distributorid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
