# Generated by Django 3.0.3 on 2020-03-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_auto_20200313_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distributorid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='distributorid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='distributorid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='distributorid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesmandetail',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='distributorid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
