# Generated by Django 3.0.3 on 2020-03-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_auto_20200313_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesmandetail',
            name='salesmanid',
            field=models.IntegerField(),
        ),
    ]
