# Generated by Django 3.0.3 on 2020-03-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_auto_20200314_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='orderamount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='orderdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentdate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
