# Generated by Django 3.0.3 on 2020-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_auto_20200314_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.CharField(max_length=100),
        ),
    ]
