# Generated by Django 3.0.3 on 2020-03-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0016_auto_20200314_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='deldate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delsalesman',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delstatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
