# Generated by Django 3.0.3 on 2020-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_auto_20200314_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pendingbalance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
